site_name: Awesome GameDev Resources
site_url: https://courses.tolstenko.net
repo_url: https://github.com/InfiniBrains/Awesome-GameDev-Resources
repo_name: InfiniBrains/Awesome-GameDev-Resources

nav:
  - Home: README.md
  - Programming:
      - intro/README.md
      - Introduction to C++: intro/01-introduction/README.md
      - Setup: intro/02-tooling/README.md
      - Data Types: intro/03-datatypes/README.md
      - Conditionals: intro/04-conditionals/README.md
      - Loops: intro/05-loops/README.md
      - Functions: intro/06-functions/README.md
      - Streams: intro/07-streams/README.md
      - Arrays: intro/08-arrays/README.md
      - Recursion: intro/09-recursion/README.md
      - Sorting: intro/10-sorting/README.md
  - Portfolio:
      - portfolio/README.md
      - Introduction: portfolio/01-introduction/README.md
      - Case Study:
        - portfolio/02-cases/README.md
        - Case Study Example: portfolio/02-cases/example.com.md
      - Portfolio Structure: portfolio/03-structure/README.md
      - Communication: portfolio/04-communication/README.md
      - Style: portfolio/05-style/README.md
      - Strategy: portfolio/06-strategy/README.md
      - Frontend: portfolio/10-frontend/README.md
      - Wordpress: portfolio/08-frontend/README.md
      - Getting Ready: portfolio/09-get-ready/README.md
      - Hosting: portfolio/07-hosting/README.md
      - Dynamic Content: portfolio/11-dynamic/README.md
      - Promoting: portfolio/12-promoting/README.md
      - Cover Letter: portfolio/13-cover-letter/README.md
      - CV: portfolio/14-cv/README.md
  - Dojo:
      - dojo/README.md
      - Full Cycle Game Dev: dojo/Full-Cycle-SDL-Development.md
#  - AI:
#      - artificialintelligence/README.md

docs_dir: .

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
#    - scheme: default
#      primary: indigo
#      accent: indigo
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
#    - scheme: slate
#      primary: indigo
#      accent: indigo
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/favicon.png
#  icon:
#    repo: fontawesome/brands/git-alt
#    logo: logo

edit_uri: edit/main/
view_uri: blob/main/

site_description: >-
  Awesome GameDev Resources

site_author: https://tolstenko.net

copyright: Copyright &copy; 2023 Tolstenko and Others

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
#  - pymdownx.magiclink:
#      repo_url_shorthand: true
#      user: InfiniBrains
#      repo: Awesome-GameDev-Resources
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
#  - git-committers:
#      repository: InfiniBrains/Awesome-GameDev-Resources
#      branch: main
#  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - same-dir
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - exclude:
      glob:
        - node_modules/*
        - buildDocs/*
        - cmake-build-debug/*
        - .cache
        - site
  - with-pdf:
      author: InfiniBrains
      copyright: Copyleft by InfiniBrains
      #cover: false
      #back_cover: true
      cover_title: Awesome GameDev Book
      cover_subtitle: InfiniBrains Community Innitiative
      #custom_template_path: TEMPLATES PATH
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      toc_level: 2
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      two_columns_level: 3
#      render_js: true
#      headless_chrome_path: headless-chromium
      #output_path: any-place/document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #debug_html: true
      #show_anchors: true
#      verbose: true
#  - optimize

extra:
  generator: false
  annotate:
    json: [ .s2 ]
  analytics:
    provider: google
    property: G-347541715
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! Help us improve this page by
#            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InfiniBrains
#    - icon: fontawesome/brands/gitter
#      link: https://gitter.im/squidfunk/mkdocs-material
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/mkdocs-material/
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/squidfunk

watch:
  - advanced
  - algorithms
  - artificialintelligence
  - datastructures
  - dojo
  - intro
  - overrides
  - portfolio