name: Documentation

on:
  push:
    branches:
      - master
      - main
env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    container: emscripten/emsdk
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory '*'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - uses: actions/cache@v2
        with:
          path: |
            "**/cpm_modules"
            "/tmp/cache/awesome-gamedev-resources"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', '/tmp/cache/awesome-gamedev-resources/*.json' ) }}

      - name: APT Update
        run: apt update

      - name: install chrome dependencies
        run: |
          apt install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils unzip gnupg2
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          apt update
          apt install -y google-chrome-stable
          alias google-chrome=google-chrome-stable
          alias chrome=google-chrome-stable
          alias chromium=google-chrome-stable
          alias chromium-browser=google-chrome-stable
          alias chrome-browser=google-chrome-stable
          CHROMEAPP=google-chrome-stable
          echo $CHROMEAPP
          CHROME_VERSION=$("$CHROMEAPP" --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
          echo $CHROME_VERSION
          VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          echo $VERSION
          wget -c -nc --retry-connrefused --tries=0 https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip
          unzip -o -q chromedriver_linux64.zip
          mv chromedriver /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      #          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#          sudo apt install ./google-chrome-stable_current_amd64.deb
#          alias chrome="/usr/bin/google-chrome-stable"
#          alias chromium="/usr/bin/google-chrome-stable"
#          alias chromium-browser="/usr/bin/google-chrome-stable"
#          alias google-chrome="/usr/bin/google-chrome-stable"

      - uses: browser-actions/setup-chrome@v1
        with:
          version: 'latest'

#      - uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen gource libgs-dev
          pip install git+https://${{ secrets.GH_SQUID_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install jinja2 Pygments mkdocs mkdocs-same-dir mkdocs-minify-plugin mkdocs-redirects mkdocs-exclude mkdocs-git-committers-plugin-2 mkdocs-git-revision-date-localized-plugin mkdocs-with-pdf beautifulsoup4==4.9.3
          npm install 

      - name: Configure
        run: emcmake cmake -S. -Bbuild -DENABLE_TEST_COVERAGE=OFF -DENABLE_STANDALONE=ON -DENABLE_DOCUMENTATION=ON

#      - name: Build Docs
#        run: cmake --build build --target GenerateDocs
#
#      - name: Build Emscripten
#        run: cmake --build build -j4 --config Release

      - name: mkdocs
        run: CI=1 mkdocs build

      - name: COPY CNAME
        run: cp CNAME ./site

#      - name: Copy Emscripten build to docs
#        run: cp -R build/out/* build/documentation/doxygen/html/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.2
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.2
            @semantic-release/git@10.0.1
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/github@8.0.7
            @semantic-release/npm@9.0.1
            @semantic-release/release-notes-generator@10.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Version
        id: version
        run: |
          if [[ ${{ steps.semantic.outputs.new_release_published }} == true ]]
          then     
            export version=v${{ steps.semantic.outputs.new_release_version }}
          else
            export version=`git describe --abbrev=0 --tags $tag`
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Latest pdf
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' #|| startsWith(github.ref, 'refs/tags')
        with:
          allowUpdates: true
          artifacts: site/pdf/document.pdf
          tag: latest

      - name: Versined pdf
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' #|| startsWith(github.ref, 'refs/tags')
        with:
          allowUpdates: true
          artifacts: site/pdf/document.pdf
          tag: ${{ steps.version.outputs.version }}